services:
  meshing-around:
    ports:
      - 8420:8420
    #devices:
      #- /dev/ttyUSB0:/dev/tty #update your config.ini to /dev/tty
      #- /dev/ttyACM0:/dev/tty #if using serial select proper port
    volumes:
      - .:/app:rw
    image: ghcr.io/spudgunman/meshing-around:main
    container_name: meshing-around
    restart: unless-stopped
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #user: "1000:1000"
    #user: "10999:10999"
    networks:
      - meshing-around-network

    test-bot:
      image: ghcr.io/spudgunman/meshing-around:main
      container_name: test-bot
      command: ["/bin/bash", "-c", "python3 modules/test_bot.py | tee /tmp/test_tmp.txt; if grep -E 'failures=|errors=' /tmp/test_tmp.txt; then cp /tmp/test_tmp.txt /app/test_results.txt; fi"]
      volumes:
        - .:/app:rw
      networks:
        - meshing-around-network
      stdin_open: true
      tty: true

  debug-console:
    image: ghcr.io/spudgunman/meshing-around:main
    container_name: debug-console
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - .:/app:rw
    networks:
      - meshing-around-network

  meshtasticd:
    ports:
      - 4403:4403
      - 443:443
    volumes:
      - ./script/docker:/etc/meshtasticd:rw
    restart: unless-stopped
    container_name: meshtasticd
    image: meshtastic/meshtasticd:daily-debian
    networks:
      - meshing-around-network

  ollama:
    ports: 
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - meshing-around-network

networks:
  meshing-around-network:
    external: true
