# Docker Compose configuration for Meshing Around.
# This setup includes the main Meshing Around service, with optional Ollama and Prometheus Node Exporter services.
# Adjust device mappings, ports, and configurations as needed for your environment.
services:
  meshing-around:
    ports:
      - 8420:8420
    #devices:
      #- /dev/ttyUSB0:/dev/tty #update your config.ini to /dev/tty
      #- /dev/ttyACM0:/dev/tty #if using serial select proper port
    volumes:
      - .:/app:rw
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    image: ghcr.io/spudgunman/meshing-around:main
    container_name: meshing-around
    restart: unless-stopped
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    extra_hosts:
      - "host.docker.internal:host-gateway" # Enables access debug-console
    #user: "1000:1000" # non-root user for better security
    #user: "10999:10999" # for Docker Desktop compatibility

  debug-console:
    image: ghcr.io/spudgunman/meshing-around:main
    container_name: debug-console
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    volumes:
      - .:/app:rw

  meshtasticd: # Optional service for Meshtastic device management.
    ports:
      - 4403:4403
      - 9443:9443
    volumes:
      - ./script/docker:/etc/meshtasticd:rw
    restart: unless-stopped
    container_name: meshtasticd
    image: meshtastic/meshtasticd:daily-debian

  ollama: # Used for enabling LLM interactions.
    ports: 
      - 11434:11434 # Ollama API port
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5