services:
  meshing-around:
    stdin_open: true
    tty: true
    ports:
      - 8420:8420
    devices: # Optional if using meshtasticd. Pass through radio device.
      - /dev/ttyUSB0
    volumes:
      - /data/meshing-around/config.ini:/app/config.ini:rw
    image: ghcr.io/SpudGunMan/meshing-around:test-all-changes

  meshtasticd: # Runs a virtual node. Optional, but can be used to link meshing-around directly to mqtt.
    ports:
      - 4403:4403
    restart: unless-stopped
    container_name: meshtasticd
    image: meshtastic/meshtasticd:beta

  ollama: # Used for enabling LLM interactions.
    ports: 
      - 11434:11434
    volumes:
      - /data/ollama:/root/.ollama
    container_name: ollama
    image: alpine/ollama